/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopupRouteImport } from './routes/topup'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ShiftRouteImport } from './routes/shift'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PosRouteImport } from './routes/pos'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHealthDbRouteImport } from './routes/api/public/health/db'

const TopupRoute = TopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftRoute = ShiftRouteImport.update({
  id: '/shift',
  path: '/shift',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthDbRoute = ApiPublicHealthDbRouteImport.update({
  id: '/api/public/health/db',
  path: '/api/public/health/db',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/cart': typeof CartRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/finance': typeof FinanceRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/pos': typeof PosRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shift': typeof ShiftRoute
  '/staff': typeof StaffRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/topup': typeof TopupRoute
  '/api/public/health/db': typeof ApiPublicHealthDbRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/cart': typeof CartRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/finance': typeof FinanceRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/pos': typeof PosRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shift': typeof ShiftRoute
  '/staff': typeof StaffRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/topup': typeof TopupRoute
  '/api/public/health/db': typeof ApiPublicHealthDbRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/cart': typeof CartRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/finance': typeof FinanceRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/pos': typeof PosRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shift': typeof ShiftRoute
  '/staff': typeof StaffRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/topup': typeof TopupRoute
  '/api/public/health/db': typeof ApiPublicHealthDbRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/cart'
    | '/customers'
    | '/dashboard'
    | '/finance'
    | '/history'
    | '/inventory'
    | '/login'
    | '/menu'
    | '/pos'
    | '/settings'
    | '/setup'
    | '/shift'
    | '/staff'
    | '/support'
    | '/team'
    | '/topup'
    | '/api/public/health/db'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/cart'
    | '/customers'
    | '/dashboard'
    | '/finance'
    | '/history'
    | '/inventory'
    | '/login'
    | '/menu'
    | '/pos'
    | '/settings'
    | '/setup'
    | '/shift'
    | '/staff'
    | '/support'
    | '/team'
    | '/topup'
    | '/api/public/health/db'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/cart'
    | '/customers'
    | '/dashboard'
    | '/finance'
    | '/history'
    | '/inventory'
    | '/login'
    | '/menu'
    | '/pos'
    | '/settings'
    | '/setup'
    | '/shift'
    | '/staff'
    | '/support'
    | '/team'
    | '/topup'
    | '/api/public/health/db'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CartRoute: typeof CartRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  FinanceRoute: typeof FinanceRoute
  HistoryRoute: typeof HistoryRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  PosRoute: typeof PosRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  ShiftRoute: typeof ShiftRoute
  StaffRoute: typeof StaffRoute
  SupportRoute: typeof SupportRoute
  TeamRoute: typeof TeamRoute
  TopupRoute: typeof TopupRoute
  ApiPublicHealthDbRoute: typeof ApiPublicHealthDbRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topup': {
      id: '/topup'
      path: '/topup'
      fullPath: '/topup'
      preLoaderRoute: typeof TopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shift': {
      id: '/shift'
      path: '/shift'
      fullPath: '/shift'
      preLoaderRoute: typeof ShiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health/db': {
      id: '/api/public/health/db'
      path: '/api/public/health/db'
      fullPath: '/api/public/health/db'
      preLoaderRoute: typeof ApiPublicHealthDbRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  CartRoute: CartRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  FinanceRoute: FinanceRoute,
  HistoryRoute: HistoryRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  PosRoute: PosRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  ShiftRoute: ShiftRoute,
  StaffRoute: StaffRoute,
  SupportRoute: SupportRoute,
  TeamRoute: TeamRoute,
  TopupRoute: TopupRoute,
  ApiPublicHealthDbRoute: ApiPublicHealthDbRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
